name: countdown

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - '6379:6379'

#  server:
#    build:
#      context: ./server
#      dockerfile: Dockerfile
#    ports:
#      - '5002:5002'
#
#  client:
#    build:
#      context: ./client
#      dockerfile: Dockerfile
#    ports:
#      - '3000:3000'
