services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - '6379:6379'
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 3s
      retries: 5
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      network: host
    env_file: ./server/.env
    ports:
      - "5002:5002"
    restart: always
    depends_on:
      redis:
        condition: service_healthy
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      network: host
    restart: always
    env_file: ./client/.env
    ports:
      - "3000:3000"
