name: countdown

services:
  web:
    image: httpd:latest
    ports:
      - "8083:80"
    volumes:
      - ./web:/usr/local/apache2/htdocs/
  redis:
    image: 'bitnami/redis:latest'
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
